name: 'build' 
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Create src directory
        run: mkdir -p src
        
      - name: Checkout private planner
        uses: actions/checkout@v3
        with:
          repository: oscardegroot/mpc_planner
          token: ${{ secrets.CI_REPO_PAT }}
          path: src/mpc_planner
          ref: 6535b3fe855f590dde8193cf6e2902f057adc8b9

      - name: Checkout private guidance planner
        uses: actions/checkout@v3
        with:
          repository: oscardegroot/guidance_planner
          token: ${{ secrets.CI_REPO_PAT }}
          path: src/guidance_planner
          ref: ec153a69ce0bb1b40b6c89f7a06c235c199ab6d8

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          # Change this to be your CI task/script
          runCmd: |
            chmod +x setup.sh
            chmod +x build.sh
            ./setup.sh -y
            ./build.sh jackalsimulator True
