name: 'build' 
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Checkout private planner
        uses: actions/checkout@v3
        with:
          repository: oscardegroot/mpc_planner
          token: ${{ secrets.CI_REPO_PAT }}
          path: mpc_planner
          ref: 32499d30aec8b2f3878e3cd1d9377a31a066310f

      - name: Checkout private guidance planner
        uses: actions/checkout@v3
        with:
          repository: oscardegroot/guidance_planner
          token: ${{ secrets.CI_REPO_PAT }}
          path: guidance_planner
          ref: ec153a69ce0bb1b40b6c89f7a06c235c199ab6d8

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.3
        with:
          # Change this to be your CI task/script
          runCmd: |
            mv mpc_planner src/mpc_planner
            mv guidance_planner src/guidance_planner
            chmod +x setup.sh
            chmod +x build.sh
            ./setup.sh
            ./build.sh jackalsimulator True
